### PR TITLE
fix: [PL-31591]: Increased ng-manager memory by 64MB

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**

### CODE REVIEW

**Comment by VikasMaddukuriHarness** [comment]
Done @Ompragash. Thanks for noticing. Modified resource limits for helm installation as well.

**Review by ankit-harness — APPROVED** [review]

**Comment by rkapoor10** [comment]
Successful pipeline run after modification. 

Installation : using Docker compose
Piepeline : [sample deployment](https://developer.harness.io/docs/continuous-delivery/onboard-cd/cd-quickstarts/harness-community-edition-quickstart/)

Delegate installation 
- if done using 4gb Memory and 4CPUs there are some intermediate issues like timeout, but pipeline run is successful 
- for 6gb Memory and 6CPUs the pipeline run is successful without any exceptions/timeout

Screenshot of successful run : 
Screenshot 2023-03-23 at 2 40 34 PM

**Comment by sean-harness** [comment]
Does this fix the CrashLoopBackOff users have been reporting?

**Comment by harnesspravin** [comment]
If CrashLoopBackOff is due to ng-manager memory constraints, then it should solve the issue.

**Pull request merged**
